#!/bin/bash

if [ $FAI_ACTION = "install" ]
then
cat >> $target/etc/fstab <<-EOF
192.168.3.1:/srv/nfs4/home /home nfs noauto,x-systemd.automount,x-systemd.device-timeout=10,timeo=14,x-systemd.idle-timeout=1min 0 0
EOF
fi
